# --- Datasource configuration ---
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
quarkus.datasource.jdbc.driver=org.h2.Driver


# --- Hibernate ORM configuration ---
quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql


# --- H2 Console (optional, for debugging) ---
quarkus.h2.console.enabled=true
quarkus.h2.console.path=/h2-console

%dev.quarkus.datasource.dev-ui.allow-sql=true
