#set-1: Enable ssl

# REST Client base URL (HTTPS)
jsonplaceholder-api/mp-rest/url=https://jsonplaceholder.typicode.com

# Enable SSL
quarkus.ssl.native=true
quarkus.http.ssl-port=8443
quarkus.http.insecure-requests=disabled


#set-1-a: JKS
# Keystore configuration
#quarkus.http.ssl.certificate.key-store-file=server-keystore.jks
#quarkus.http.ssl.certificate.key-store-password=changeit
#quarkus.http.ssl.certificate.key-store-provider=JKS

#set-1-b: P12
# Keystore configuration
quarkus.http.ssl.certificate.key-store-file=server-keystore.p12
quarkus.http.ssl.certificate.key-store-password=changeit
quarkus.http.ssl.certificate.key-store-provider=PKCS12

#GET https://localhost:8443/consume-users




#set-2: Eisable ssl

# REST Client base URL (HTTP)
#jsonplaceholder-api/mp-rest/url=http://jsonplaceholder.typicode.com

# Disable SSL
#quarkus.ssl.native=false
#quarkus.http.insecure-requests=enabled


#GET http://localhost:8080/consume-users
