# Reactive datasource
quarkus.datasource.db-kind=mariadb
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.reactive.url=mysql://localhost:3306/quarkus_db_2

# Hibernate Reactive ORM
#quarkus.hibernate-orm.datasource.generation=create
#quarkus.hibernate-orm.log.sql=true


# --- Hibernate ORM configuration ---
quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql
