quarkus.http.port=8080

# Reactive datasource
quarkus.datasource.db-kind=mariadb
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.reactive.url=mysql://localhost:3306/quarkus_db_2


# --- Hibernate ORM reactive configuration ---
#quarkus.hibernate-orm.database.generation=create
#quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# Enable OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true

#http://localhost:8080/openapi
#http://localhost:8080/swagger-ui

# Root log level
quarkus.log.level=INFO

# Hibernate SQL logs
#quarkus.hibernate-orm.log.sql=true

# Category-specific logging
quarkus.log.category."com.rk.quarkus".level=DEBUG

# Enable file logging
quarkus.log.file.enable=true
quarkus.log.file.path=logs/quarkus.log
quarkus.log.file.rotation.max-file-size=10M
quarkus.log.file.rotation.max-backup-index=5
